---
abstract: 'Translates common ls formats into a hashref.'
author:
  - 'Michael Ching <michaelc@wush.net>'
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-Ls
no_index:
  directory:
    - inc
    - t
requires:
  POE::Filter::Line: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: '0.02'
